version: '2'
services:
  §§INSTANCE-jupyter-datascience-notebook:
    image: jupyter/datascience-notebook
    container_name:  §§INSTANCE-jupyter-datascience-notebook
    ports:
      - "§§PORT:8888"
    environment:
     - PASSWORD=§§JUPYTER_PASSWORD
    volumes_from: 
      - §§INSTANCE-jupyter-datascience-notebook-data    

  §§INSTANCE-jupyter-datascience-notebook-data:
    image: busybox
    container_name: §§INSTANCE-jupyter-datascience-notebook-data
    volumes:
      - ./home/jovyan/work:/home/jovyan/work
      
  