version: '3'

services:
  bibbox-jupyter-tensorflow-notebook:
    image: jupyter/datascience-notebook
    container_name:  bibbox-jupyter-datascience-notebook
    restart: unless-stopped
    ports:
      - "8065:8888"
    environment:
     - PASSWORD=vendetta
     - NotebookApp.token=vendetta
     - NotebookApp.password=vendetta     
    volumes:
      - ./data/work:/home/jovyan/work
    command: "start-notebook.sh --NotebookApp.token='vendetta' --NotebookApp.allow_origin='localhost:8065'"
